version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3100:3100"
    networks:
      - redbicis

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "3000:3000"
    volumes:
      - ./bicicletas.db:/back/database/bicicletas.db
    networks:
      - redbicis

networks:
  redbicis:
